Edge replicant
Transport-for-the-North/NorMITs-Demand pull request #963
Opened 2022-10-12 09:27 UTC by mishtaiwi

Brought in the EDGE growth functions under normits_demand/models/forecasting/edge_forecast.py
Call main function in normits_demand/models/forecasting/edge_replicant.py

Add the Cube export/file copying process and functions under normits_demand\utils being: c01_ExportCubeFunctions and r01_RunExportCube

2022-10-12 13:15 UTC, BenTaylor-TfN commented
Will need to tidy this up with Matt's branch: https://github.com/Transport-for-the-North/NorMITs-Demand/tree/edge_replicant

Can discuss later

2022-10-13 09:21 UTC, BenTaylor-TfN commented
I've made some initial changes to the code detailed below:

- Tided up imports - plenty of import weren't being used
- Formatted code with black - coding standards, easier to read
- Removed some `pd.options.mode.chained_assignment = None` lines
- Various bit of tidying
    - All this does is supress warnings. Deal with these warnings at the source instead.
- Moved files around
    - normits_demand/utils/c01_ExportCubeFunctions.py -> normits_demand/tools/edge_cube_extractor.py
        - Hopefully this is a tool at some point - just needs wrapping in a nice class / run-function
        - Also allows linking in with the rest of the EDGE replicant in future. That is, if the setup hasn't been done yet, just run the setup tool automatically.
    - normits_demand/utils/r01_RunExportCube.py run_tools/run_edge_cube_extractor.py
        - Links into the above point, making this a simple "setup and run" script.

2022-10-13 11:30 UTC, BenTaylor-TfN commented
I'm now finished with my review/changes in the code for now. The code is now ready for a bit more of an in-depth review.

A couple of points from my review @mishtaiwi:
- variable/function naming should be all lower-case with underscores. There should never be an upper-case letter in a variable/function name.
    - Classes are a bit different. See the guide [here](https://google.github.io/styleguide/pyguide.html#3164-guidelines-derived-from-guidos-recommendations).
- Add type hints to functions 
- Run PyLint, MyPy (once type hints added), black, and PyDocStyle for general guidance on how to follow the standards.

Things for the next reviewer to keep an eye out for:
- Look for places that functionality can be replaced with framework functionality.
    - A good example of this is the `edge_cube_extractor.CheckFileExists`. There's already utils in the framework to do this.
- Note places code may need a refactor to fit with framework, even if not able to make changes now
- Keep an eye out for inconsistencies with the general flow of things in demand.
- Logging needs bringing into line with rest of demand so logging messages are picked up correctly.
    - I've chucked together an example in the cube extractor run/tool scripts

Happy to send over a copy of the coding standards if you want a look. Let's focus on getting 80% of the way there for now and hit all the main points. It doesn't have to be perfect if other work needs doing.

2022-11-02 15:09 UTC, wsp-mbuckley requested changes
Finished review most of the comments are fairly simple fixes and I think most aren't causing any errors in the process. One place where there is an error is on line 490 in `edge_forecast` where the internal flag isn't being set to 1 for internal zones.

Some other general points:
- Use `.loc` when setting values in DataFrames instead of just square brackets, not using `.loc` can sometimes cause errors
- The docstrings aren't following TfN's format, the first line in the docstring should have a brief explanation of the function / class with a more detailed explanation just below
- Reiterate Ben's points about type annotations, variable names and running pylint, mypy, black etc.

I think most of the comments should be fairly self-explanatory but we could have a chat about some of the areas where I've suggested using functionality already available in NorMITs demand.

2022-11-15 14:23 UTC, wsp-mbuckley requested changes
Thanks for sorting out all the previous comments, just a few more mostly about return type annotations and docstring format we use the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).

There was an issue with the tool not running from `run_forecast` which should be fix with the following 2:
- Update the config class validation of `edge_factors_path`
- Line 139 in `run_forecast` needs updating to run the new function `run_edge_growth`

Then just test that it works with `run_forecast`

2022-11-15 14:23 UTC, wsp-mbuckley commented on normits_demand/tools/edge_cube_extractor.py
> +        overwrite_tlc = overwrite_tlcs.at[i, "Overwrite"]
You can get the values directly from the row e.g. `row["NoRMS"]`

2022-11-15 14:23 UTC, wsp-mbuckley commented on normits_demand/tools/edge_cube_extractor.py
> +    None.
unneeded

2022-11-15 14:23 UTC, wsp-mbuckley commented on normits_demand/tools/edge_cube_extractor.py
> +    omx_file = omx.open_file(pathlib.Path(out_path, f"{out_csv}.omx"))
`OMXFile` should be able to handle this now

2022-11-15 14:23 UTC, wsp-mbuckley commented on normits_demand/tools/edge_cube_extractor.py
> +
This should now work with CUBE OMX files

2022-11-15 14:23 UTC, wsp-mbuckley commented on normits_demand/tools/edge_cube_extractor.py
> +    None.
remove

2022-11-15 14:23 UTC, wsp-mbuckley commented on normits_demand/tools/edge_cube_extractor.py
> +    )
the `subprocess.run` function can be used instead

2022-11-15 14:23 UTC, wsp-mbuckley commented on normits_demand/tools/edge_cube_extractor.py
> +
remvoe

2022-11-15 14:23 UTC, wsp-mbuckley commented on normits_demand/tools/edge_cube_extractor.py
> +    proc_single(
Use `subprocess.run`

2022-11-15 14:23 UTC, wsp-mbuckley commented on run_models/run_forecast.py
> +        edge_replicant.run_edge_growth(params)
Use `edge_replicant.run_edge_growth`

2022-11-15 14:23 UTC, wsp-mbuckley commented on run_tools/run_edge_cube_extractor.py
> +from pathlib import Path
group pathlib with built-in imports

2022-11-15 14:23 UTC, wsp-mbuckley commented on run_tools/run_edge_cube_extractor.py
> +            Path(CUBE_CAT_RUN_PATH, f"Outputs/BaseAssign/{period}_stn2stn_costs.csv")
You can use the `'/'` operator instead e.g. `CUBE_CAT_RUN_PATH / f"Outputs/BaseAssign/{period}_stn2stn_costs.csv"`

2022-11-15 15:27 UTC, BenTaylor-TfN commented
Noting down some methodology questions/notes from my review. I want to make sure I understand why all the design decisions have been made.
@mishtaiwi - we may want a call to go through this in detail.
Let's add items to the forecasting backlog after discussion


### Questions
- Perhaps it makes sense to make an "EdgeReplicant" class / model to facilitate the following questions/changes
  - How much work would it be to allow the user to input a list of years and get the process to run for all years?
- Currently there are no outputs until the very end of the process (meaning that if it crashes before the end, we get nothing). 
  - Could we introduce a "Checkpointing" process where we output the matrices once they have been grown
  - Then we have a separate "output" step which aggregates the matrices to the output format
- Why does the cube extractor output 100+ matrices? Are there truly this many distinct growth factors? Can we aggregate these before input at all?
  - Could we introduce some sort of normalised naming convention that separate from NoRMS? Making it obvious which matrices are using which growth factors e.g. "hb_external_reduced_ticket...csv"
- `I:\NorMITs Demand\import\edge_replicant\apply_growth\Segments2UCs.csv` links input matrices to userclasses. Does it makes sense to add the growth method and internal / external to here instead of hardcoding it?
- It's currently a quite slow process. We could multiprocess it. Is there anything (memory / accessing the same data) you think would stop us from multiprocessing this?
- The process currently prints out base and future demand as it is running. I'm aware this is added to a log file during run, but it would be nice / cleaner to get this output as a singe log file

2022-11-24 14:39 UTC, BenTaylor-TfN approved these changes

2022-11-24 14:40 UTC, merged